const DummyDataSets = {
  highCardRates: [
    {
      id: 1,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
    {
      id: 2,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
    {
      id: 3,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
    {
      id: 4,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
    {
      id: 5,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
    {
      id: 6,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
    {
      id: 7,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
    {
      id: 8,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
    {
      id: 9,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
    {
      id: 10,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
    {
      id: 11,
      title: "All uk steam card",
      type: "Naira Rate",
      rate: 600,
    },
  ],

  giftCardtransactionData: [
    {
      id: 1,
      logo: require("../assets/images/logo.png"),
      category: "Amazon card",
      type: "Amazon US",
      subSatus: "Your card was Approved",
      priceOnCard: 150.0,
      rate: "456/$",
      amountReceived: "250,000",
      status: "Successful",
      Date: new Date("2023-9-14"),
      Time: "10:24pm",
    },
    {
      id: 2,
      logo: require("../assets/images/logo.png"),
      category: "Amazon card",
      type: "Amazon US",
      subSatus: "Your card was Approved",
      priceOnCard: 150.0,
      rate: "456/$",
      amountReceived: "250,000",
      status: "Successful",
      Date: new Date("2023-9-14"),
      Time: "10:24pm",
    },
  ],
  withdrawalData: [
    {
      id: 20,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 1",
      bankName: "ACCESS BANK",
      acctNumber: "0723456787",
      acctName: "Joy wilson",
      price: 150.00,
      status: "Successful",
      Date: new Date("2023-9-14"),
      Time: "8: 30pm",
    },
    {
      id: 21,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 1",
      bankName: "Lorem ipsum dolor sit amet",
      price: 150.0,
      status: "Successful",
      Date: new Date("2023-9-14"),
    },
    {
      id: 22,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 1",
      bankName: "Lorem ipsum dolor sit amet",
      price: 150.0,
      status: "Successful",
      Date: new Date("2023-9-14"),
    },
    {
      id: 1,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 1",
      bankName: "Lorem ipsum dolor sit amet",
      price: 150.0,
      status: "Successful",
      Date: new Date("2023-9-14"),
    },
    {
      id: 2,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 2",
      bankName: "Consectetur adipiscing elit",
      price: 75.5,
      status: "Pending",
      Date: new Date("2023-9-14"),
    },
    {
      id: 3,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 3",
      bankName: "Lorem ipsum dolor sit amet",
      price: 150.0,
      status: "Failed",
      Date: new Date("2023-9-14"),
    },

    {
      id: 4,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 4",
      bankName: "Lorem ipsum dolor sit amet",
      price: 150.0,
      status: "Successful",
      Date: new Date("2023-9-14"),
    },
    {
      id: 5,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 5",
      bankName: "Consectetur adipiscing elit",
      price: 75.5,
      status: "Pending",
      Date: new Date("2023-9-14"),
    },
    {
      id: 6,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 6",
      bankName: "Lorem ipsum dolor sit amet",
      price: 150.0,
      status: "Failed",
      Date: new Date("2023-8-3"),
    },
    {
      id: 7,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 7",
      bankName: "Lorem ipsum dolor sit amet",
      price: 150.0,
      status: "Successful",
      Date: new Date("2023-8-3"),
    },
    {
      id: 8,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 8",
      bankName: "Consectetur adipiscing elit",
      price: 75.5,
      status: "Pending",
      Date: new Date("2023-8-3"),
    }, 
    {
      id: 9,
      logo: require("../assets/images/logo.png"),
      title: "Transaction 9",
      bankName: "Lorem ipsum dolor sit amet",
      price: 150.0,
      status: "Failed",
      Date: new Date("2023-7-3"),
    },
  ],

  notificationData: [
    {
      id: 1,
      title: "Sample Title",
      date: "2023-10-15",
      time: "10:00am",
      description: "This is a sample description.",
    },
    {
      id: 2,
      title: "Sample Title",
      date: "2023-10-15",
      time: "10:00am",
      description: "This is a sample description.",
    },
    {
      id: 3,
      title: "Sample Title",
      date: "2023-10-15",
      time: "10:00am",
      description: "This is a sample description.",
    },
    {
      id: 4,
      title: "Sample Title",
      date: "2023-10-15",
      time: "10:00am",
      description: "This is a sample description.",
    },
    {
      id: 5,
      title: "Sample Title",
      date: "2023-10-15",
      time: "10:00am",
      description: "This is a sample description.",
    },
  ],
};

export default DummyDataSets;
